name: Raghvita_Auto_Engine
on:
  schedule:
    - cron: '0 */3 * * *'  # Har 3 ghante mein (UTC time)
  workflow_dispatch:      # Manual button bhi rahega
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install axios
      - name: Run AI & Deploy
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          node scripts/generator.js
          git config --global user.name "Basant Kumar"
          git config --global user.email "raghvitaenterprises@gmail.com"
          git add .
          git commit -m "Auto-Update: SarkariResNova V2 Article" || echo "No changes"
          git push origin main
          npx firebase-tools deploy --only hosting:sarkariresnova-site --token "$FIREBASE_TOKEN" --project affiearn-ad591
